title: alexx.fyi
description: Personal blog and pages for alexx.fyi
url: "https://alxndrrr.github.io"
baseurl: "/alexx.fyi"
lang: en

author:
  name: Alex van der Weij
  email: "hi@alexx.fyi"
  threads: "https://www.threads.net/@alxndrr.nl"

logo: "/assets/img/avatar.png"
micro_logo: "/assets/img/avatar.png"

theme_color: "#18171c"
accent_color: "#ff0073"

permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

nav:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Favorites
    url: /favorites/
  - title: Colophon
    url: /colophon/

mobile_nav:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Favorites
    url: /favorites/
  - title: Colophon
    url: /colophon/

social_links:
  - title: Threads
    url: "https://www.threads.net/"
    icon: "fa-brands fa-threads"
  - title: RSS
    url: "/feed.xml"
    icon: "fa-solid fa-rss"
  - title: Mail
    url: "mailto:hello@example.com"
    icon: "fa-solid fa-envelope"
